# -*- coding: utf-8 -*-
"""PDF -> fragment HTML, đóng vai pandoc cho nhánh .pdf.

Sách PDF trong tủ này là sách in được quét/dựng lại rồi in ra PDF, nên:

- **không có heading, không có đoạn** — PDF chỉ có dòng đặt ở toạ độ. Đoạn văn
  phải suy ra từ thụt lề dòng đầu và từ dòng kết thúc sớm (chữ căn đều hai bên
  thì dòng nào cũng chạm lề phải, trừ dòng cuối đoạn);
- **hình vẽ là nét vector, không phải ảnh nhúng** — `get_images()` trả về rỗng
  dù trang đầy hình. Phải gom các nét gần nhau thành cụm rồi *render* cụm đó ra
  PNG;
- **số hiệu hình ("18", "105") là text nằm đè lên hình**, nên vừa phải giữ nó
  trong ảnh render, vừa phải nhặt nó ra khỏi dòng chữ — không thì giữa đoạn văn
  mọc ra một đoạn toàn số.

Đầu ra giống hệt `run_pandoc`: fragment HTML với `<img src="data:...">`, cộng
thêm thư mục ảnh PNG để `media_index()` tra ngược. Nhờ vậy build_book.py không
cần biết nguồn là docx hay pdf.

Cần `pymupdf` (`pip install pymupdf`) — chỉ lúc chuyển đổi, app vẫn không có
phụ thuộc nào.
"""
import base64
import collections
import html as H
import io
import pathlib
import re

# Rác của công cụ tạo PDF, xuất hiện lại trên từng trang.
JUNK = re.compile(r'Foxit PDF Creator|foxitsoftware\.com|For evaluation only'
                  r'|Generated by', re.I)
LABEL = re.compile(r'^\d{1,3}[A-Za-z]?$')      # số hiệu hình: 18, 105, 124A

BOLD, ITALIC = 1 << 4, 1 << 1


def _merge_rects(rects, pad, page_rect):
    """Gom các nét vẽ nằm gần nhau thành từng cụm hình."""
    import fitz
    boxes = []
    for r in rects:
        r = fitz.Rect(r)
        # Khung viền cả trang / nền: không phải hình minh hoạ.
        if r.width > page_rect.width * 0.92 and r.height > page_rect.height * 0.8:
            continue
        if r.is_empty or r.is_infinite:
            continue
        boxes.append(r)

    changed = True
    while changed:
        changed = False
        out = []
        for b in boxes:
            grown = fitz.Rect(b) + (-pad, -pad, pad, pad)
            hit = None
            for o in out:
                if fitz.Rect(o).intersects(grown):
                    hit = o
                    break
            if hit is None:
                out.append(fitz.Rect(b))
            else:
                hit |= b
                changed = True
        boxes = out
    return boxes


def _overlap(a, b):
    """Tỉ lệ diện tích của a nằm trong b."""
    import fitz
    inter = fitz.Rect(a) & fitz.Rect(b)
    area = fitz.Rect(a).get_area()
    return (inter.get_area() / area) if area else 0.0


def _runs(spans):
    """[span] -> HTML, gộp các span cùng kiểu chữ thành một <strong>/<em>."""
    out, cur, style = [], [], None

    def flush():
        if not cur:
            return
        s = H.escape(''.join(cur))
        if not s.strip():
            out.append(s)
        else:
            b, i = style
            if b:
                s = '<strong>%s</strong>' % s
            if i:
                s = '<em>%s</em>' % s
            out.append(s)
        cur.clear()

    for sp in spans:
        st = (bool(sp['flags'] & BOLD), bool(sp['flags'] & ITALIC))
        if sp['text'].strip() == '':      # khoảng trắng thì theo kiểu đang mở
            st = style if style is not None else st
        if st != style:
            flush()
            style = st
        cur.append(sp['text'])
    flush()
    return ''.join(out)


def _page_items(page, dpi, pad, min_w, min_h, dropped_log):
    """Một trang -> [(y, kind, payload)] theo thứ tự đọc từ trên xuống."""
    import fitz

    figs = [r for r in _merge_rects([d['rect'] for d in page.get_drawings()],
                                    pad, page.rect)
            if r.width >= min_w and r.height >= min_h]

    raw = page.get_text('dict')
    lines = []
    for blk in raw['blocks']:
        if blk['type'] == 1:              # ảnh bitmap nhúng (hiếm)
            figs.append(fitz.Rect(blk['bbox']))
            continue
        for ln in blk['lines']:
            txt = ''.join(s['text'] for s in ln['spans'])
            if JUNK.search(txt):
                continue
            box = fitz.Rect(ln['bbox'])
            inside = next((f for f in figs if _overlap(box, f) > 0.7), None)
            if inside is not None:
                if txt.strip():
                    dropped_log.append((page.number + 1, txt.strip()))
                continue
            lines.append((box, ln['spans'], txt))

    # Số trang: dòng chỉ có chữ số, nằm dưới cùng.
    body = [l for l in lines
            if not (l[0].y0 > page.rect.height - 60 and l[2].strip().isdigit())]

    items = list(_paragraphs(body, page.rect, figs))
    for f in figs:
        labels = []
        for blk in raw['blocks']:
            if blk['type'] == 1:
                continue
            for ln in blk['lines']:
                t = ''.join(s['text'] for s in ln['spans']).strip()
                if LABEL.match(t) and _overlap(fitz.Rect(ln['bbox']), f) > 0.5:
                    labels.append((ln['bbox'][0], t))
        clip = fitz.Rect(f) + (-4, -4, 4, 4)
        clip &= page.rect
        png = page.get_pixmap(clip=clip, dpi=dpi,
                              colorspace=fitz.csGRAY).tobytes('png')
        items.append((f.y0, 'fig', (png, [t for _, t in sorted(labels)])))

    items.sort(key=lambda it: it[0])
    return items


def _mode(values, bin_size=3):
    """Giá trị hay gặp nhất (làm tròn theo bin) — lề của khối chữ chính.

    Không dùng min/max: một chữ "N" của đồ hình la bàn nằm lấn ra lề phải là đủ
    để mọi dòng còn lại trông như "kết thúc sớm", và thế là mỗi dòng thành một
    đoạn.
    """
    if not values:
        return None
    hist = collections.Counter(round(v / bin_size) for v in values)
    best = hist.most_common(1)[0][0]
    return max(v for v in values if round(v / bin_size) == best)


def _is_head(spans):
    fonts = {s['font'].split('+')[0] for s in spans if s['text'].strip()}
    return bool(fonts) and all('Tahoma' in f for f in fonts)


BULLET = {'-', '–', '—', '•', '*', 'o', '+'}


def _glue_bullets(lines):
    """Dấu đầu dòng nằm riêng một 'dòng' -> dán vào đầu dòng chữ kế nó.

    Danh sách gạch đầu dòng trong Word in ra PDF thành hai cột: dấu gạch một
    cột, chữ một cột. Không dán lại thì cả cuốn sách rải rác những đoạn chỉ có
    đúng một dấu "-", còn dòng chữ thì mất dấu.
    """
    out, pending = [], None
    for box, spans, txt in lines:
        if txt.strip() in BULLET:
            pending = (box, spans, txt)
            continue
        if pending is not None and txt.strip():
            box = box | pending[0]
            # Dấu gạch đầu dòng hay được đánh đậm trong Word; giữ nguyên thì
            # cả cuốn sách đầy những "<strong>-</strong>" chẳng để làm gì.
            mark = [dict(s, flags=0) for s in pending[1]]
            spans = mark + spans
            txt = pending[2].strip() + ' ' + txt
            pending = None
            out.append((box, spans, txt, True))   # chắc chắn là đầu một đoạn
            continue
        out.append((box, spans, txt, False))
    return out


def _paragraphs(lines, page_rect, figs=()):
    """Dòng rời -> đoạn văn, dựa vào thụt lề dòng đầu và dòng kết thúc sớm."""
    import fitz
    lines = _glue_bullets(lines)
    body = [l for l in lines if l[2].strip()]
    if not body:
        return []
    left = _mode([l[0].x0 for l in body])

    # Lề phải phải tính *theo lân cận*, không theo cả trang: chỗ chữ chạy vòng
    # quanh một hình, cột chữ hẹp lại cả chục dòng liền, mà khung ảnh Word chừa
    # ra thường rộng hơn vệt mực nên không suy ra được từ toạ độ hình.
    xs = [l[0].x1 for l in body]
    near = {}
    for k in range(len(body)):
        lo, hi = max(0, k - 4), min(len(xs), k + 5)
        near[id(body[k][0])] = _mode(xs[lo:hi])

    def beside_fig(box):
        """Dòng có nằm *cạnh* một hình (chữ chạy vòng quanh hình) không?

        Word bọc chữ ôm sát viền hình: cột chữ còn lại vừa hẹp vừa so le, một
        dòng in ra có khi bị cắt thành mấy mảnh cách nhau cả gang. Ở vùng đó cả
        thụt lề lẫn độ dài dòng đều không nói lên điều gì về chỗ hết đoạn.
        """
        return any(f.y0 < box.y1 - 4 and f.y1 > box.y0 + 4
                   and (box.x1 <= f.x0 or box.x0 >= f.x1) for f in figs)

    def margin(box):
        r = near.get(id(box), max(xs))
        for f in figs:
            if f.x0 > box.x0 + 20 and f.y0 < box.y1 and f.y1 > box.y0:
                r = min(r, f.x0)
        return r

    paras, cur, start_new = [], [], True
    prev = None
    for box, spans, txt, bullet in lines:
        if not txt.strip():               # dòng trắng: ngắt đoạn
            start_new = True
            continue
        if bullet:
            start_new = True
        elif prev is not None:
            wrap = beside_fig(prev[0]) and beside_fig(box)
            gap = box.y0 - prev[0].y1
            indent = box.x0 > left + 12
            short = prev[0].x1 < margin(prev[0]) - 30
            head = _is_head(spans) != _is_head(prev[1])
            if head or (not wrap and (indent or short or gap > 10)):
                start_new = True
        if start_new and cur:
            paras.append(cur)
            cur = []
        cur.append((box, spans))
        start_new = False
        prev = (box, spans, txt)
    if cur:
        paras.append(cur)

    out = []
    for p in paras:
        spans = [s for _, sps in p for s in sps]
        html = ' '.join(_runs(spans).split())
        if not re.sub(r'<[^>]+>', '', html).strip():
            continue
        sizes = [s['size'] for s in spans if s['text'].strip()]
        fonts = {s['font'].split('+')[0] for s in spans if s['text'].strip()}
        big = max(sizes) if sizes else 0
        # Tiêu đề in bằng font khác thân bài (Tahoma ở sách này) — chỉ để đánh
        # dấu cho dễ nhìn trong blocks.txt; cấu trúc thật vẫn do plan quyết định.
        tag = 'p'
        if fonts and all('Tahoma' in f for f in fonts):
            tag = 'h1' if big >= 14 else 'h2'
        out.append((p[0][0].y0, 'para', (tag, html)))
    return out


def pdf_to_html(pdf, out_html, media_dir, dpi=150, pad=10, min_w=40, min_h=28):
    """Trả về (html, thư_mục_ảnh, [(trang, chữ bị nuốt vào hình)])."""
    import fitz

    media_dir = pathlib.Path(media_dir)
    media_dir.mkdir(parents=True, exist_ok=True)
    for old in media_dir.glob('fig*.png'):
        old.unlink()

    doc = fitz.open(str(pdf))
    parts, dropped, n = [], [], 0
    for page in doc:
        for _, kind, payload in _page_items(page, dpi, pad, min_w, min_h, dropped):
            if kind == 'fig':
                png, labels = payload
                name = 'fig%03d.png' % n
                (media_dir / name).write_bytes(png)
                n += 1
                cap = ' '.join(labels)
                parts.append('<p><img src="data:image/png;base64,%s" alt="%s"></p>'
                             % (base64.b64encode(png).decode(), H.escape(cap)))
            else:
                tag, html = payload
                parts.append('<%s>%s</%s>' % (tag, html, tag))
    doc.close()

    html = '\n'.join(parts) + '\n'
    pathlib.Path(out_html).write_text(html, encoding='utf-8')
    return html, media_dir, dropped


def caption_hints(media_dir, raw):
    """{'IMG3': 'Hình 18 – 21'} suy từ số hiệu in trên hình."""
    hints = {}
    for i, m in enumerate(re.finditer(r'<img[^>]*alt="([^"]*)"', raw)):
        labels = m.group(1).split()
        if labels:
            hints['IMG%d' % i] = 'Hình ' + condense(labels)
    return hints


def condense(labels):
    """['18','19','20','21','105'] -> '18 – 21, 105'."""
    out, run = [], []

    def flush():
        if not run:
            return
        if len(run) >= 3:
            out.append('%s – %s' % (run[0], run[-1]))
        else:
            out.extend(run)
        run.clear()

    for t in labels:
        if run and t.isdigit() and run[-1].isdigit() and int(t) == int(run[-1]) + 1:
            run.append(t)
        else:
            flush()
            run.append(t)
    flush()
    return ', '.join(out)
